data:
  dataset: ego4d_htego
  type: normal
  # ego4d_root: pssd:s3://ego4d/all_videos_fps30_short320_chunked/
  ego4d_root: cluster1:s3://videos/ego4d/videos_short320_chunked_15s/
  ego4d_metadata: /mnt/petrelfs/share_data/xujilan/avion_metadata/ego4d_train.csv
  ego4d_metadata_aux: null
  ego4d_video_chunk_len: 15
  ego4d_fps: 30

  howto_root: cluster1:s3://howto_ego/htm_clips_15s_25fps_short128/
  howto_metadata: /mnt/hwfile/internvideo/share_data/xujilan/howto100/Howto-Interlink-egoonly_egolabel.csv
  howto_video_chunk_len: 15 # -1
  howto_fps: 25 # -1

  clip_length: 16
  clip_stride: 4
  input_size: 224
  patch_size: 16
  is_trimmed: true

  context_length: 77 # 128
  vocab_size: 49408
  norm_style: clip
  fused_decode_crop: true
  decode_threads: 1
  
  multiview: false
  clear_narration: false
  return_uid: false
  
model:
  name: CLIP_VITB16
  # norm_embed: true
  clip_length: ${data.clip_length}
  # contrastive_use_vissl: true   #use contrastive implementation in vissl
  temperature_init: 0.07
  
  freeze_temperature: true
  grad_checkpointing: true
  use_fast_conv1: true
  use_flash_attn: true
  patch_dropout: 0.0
  drop_path_rate: 0.0
  pretrain_zoo: intern
  pretrain_path: null
  project_embed_dim: 512

  multiview: ${data.multiview}

train:
  task: vlp
  batch_size: 16
  epochs: 10
  warmup_epochs: 1
  lr: 1e-5
  fix_lr: true
  lr_start: 6e-8
  lr_end: 6e-7
  grad_clip_norm: null
  update_freq: 1
  seed: 0
  workers: 10

  optimizer:
    name: adamw
    wd: 0.01
    betas: [0.9, 0.999]
    eps: 1e-8

  eval_freq: 1
  print_freq: 10
  save_freq: 1
  disable_amp: false

  use_half: false
  find_unused_parameters: false

  local_loss: false
  gather_with_grad: false
  use_zero: false

  use_multi_epochs_loader: false

test:
  # batch_size: ${train.batch_size}
  batch_size: 16
  workers: 10
  testonly: false
  savemetaonly: false
  ek100_mir:
    metapath: /mnt/petrelfs/peibaoqi/robot/epic_kitchen/
    metadata: ${test.ek100_mir.metapath}EPIC_100_retrieval_test.csv
    relevancy_path: /mnt/petrelfs/peibaoqi/robot/epic_kitchen/relevancy/caption_relevancy_EPIC_100_retrieval_test.pkl
  

    root: cluster2:s3://epic/epic_video_320p/
    video_chunk_len: -1
    fps: -1
    clip_length: 4
    clip_stride: 16
    num_clips: 1
    num_crops: 1
    sparse_sample: false
    decode_threads: ${data.decode_threads}
    fused_decode_crop: ${data.fused_decode_crop}
    

wandb: false
resume: null
resume_pretrain: null
output_dir: /mnt/petrelfs/peibaoqi/exps/avion/debug/
local_rank: 0

visualisation: false

