_base_: '../default_clip_base.yml'
data:
  dataset: ego4d_htego
  # ego4d_root: pssd:s3://ego4d/all_videos_fps30_short320_chunked/
  ego4d_root: cluster1:s3://videos/ego4d/videos_short320_chunked_15s/
  ego4d_metadata: /mnt/petrelfs/peibaoqi/robot/annotation/ego4d_new_recaption_final.csv

  howto_metadata: /mnt/petrelfs/share_data/xujilan/annotations/howto100m/Howto-Interlink-egoonly_egolabel.csv

  clip_length: 4
  clip_stride: 16
  
train:
  task: vlp
  batch_size: 128
  epochs: 15
  lr: 4e-5
  fix_lr: true

model:
  name: CLIP_VITB16
  ckpt_path: /mnt/petrelfs/peibaoqi/robot/mae/ckpt/ViT-B-16.pt
  freeze_temperature: true
  lavila_path: dont_use
wandb: true

#resume: checkpoint_best.pt

output_dir: output/
use_eva: False
use_bert: False

