_base_: '../default_clip_base.yml'
data:
  dataset: ego4d_htego

  ego4d_root: cluster1:s3://videos/ego4d/videos_short320_chunked_15s/
  ego4d_metadata: /mnt/petrelfs/peibaoqi/robot/annotation/ego4d_new_recaption_final.csv

  #egoexo4d_root: cluster1:s3://howto_ego/htm370k_cooking_clips_15s_short256/
  exoego4d_root: sssdpbq:s3://video_pub/howto100m
  # egoexo4d_metadata: /mnt/petrelfs/xujilan/data/howto100/Howto-Interlink7M/Howto-Interlink-cookingclips.csv
  egoexo4d_metadata: /mnt/petrelfs/share_data/xujilan/annotations/howto100m/Howto-Interlink-egoonly_egolabel.csv
  howto_metadata: /mnt/petrelfs/share_data/xujilan/annotations/howto100m/Howto-Interlink-egoonly_egolabel.csv
  # howto_metadata: /mnt/petrelfs/peibaoqi/robot/ego_annotation/howto_caption.csv
  how2_traj_metadata: /mnt/petrelfs/peibaoqi/EgoVideo/how2_traj
  ego4d_traj_metadata: /mnt/petrelfs/peibaoqi/EgoVideo/ego4d_traj
  clip_length: 4
  clip_stride: 16
  
train:
  task: vlp
  batch_size: 128
  epochs: 15
  lr: 4e-5
  fix_lr: true

model:
  name: CLIP_VITB16
  ckpt_path: /mnt/petrelfs/peibaoqi/robot/mae/ckpt/ViT-B-16.pt
  freeze_temperature: true
  lavila_path: /mnt/petrelfs/peibaoqi/AVION/clip_ckpt/avion_pretrain_lavila_vitb
wandb: true
resume: /mnt/petrelfs/peibaoqi/robot/mae/ckpt/base_best.pt

output_dir: /mnt/petrelfs/peibaoqi/exps/avion3/
use_eva: False
use_bert: False

